### ISSUE TITLE
when i submit S3Topology.java to storm cluster ,below is error info

### ISSUE THREAD

**Issue by lipengyuntian** [wurstmeister/storm-s3#3]
java.lang.NoClassDefFoundError: backtype/storm/tuple/ITuple at org.apache.storm.s3.bolt.S3Bolt.prepare(S3Bolt.java:43) at backtype.storm.daemon.executor$fn__3498$fn__3510.invoke(executor.clj:674) a

**Comment by wurstmeister** [comment]
which version of storm are you deploying to? ITuple was added in 0.9.3 (STORM-428)
